export const FETCH_SERVICES_REQUEST = "FETCH_SERVICES_REQUEST";
export const FETCH_SERVICES_FAILURE = "FETCH_SERVICES_FAILURE";
export const FETCH_SERVICES_SUCCESS = "FETCH_SERVICES_SUCCESS";
export const FETCH_SINGLE_SERVICE_REQUEST = "FETCH_SINGLE_SERVICE_REQUEST";
export const FETCH_SINGLE_SERVICE_FAILURE = "FETCH_SINGLE_SERVICE_FAILURE";
export const FETCH_SINGLE_SERVICE_SUCCESS = "FETCH_SINGLE_SERVICE_SUCCESS";
